# Generated by Django 5.0.6 on 2024-07-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('subtitle', models.CharField(max_length=255)),
                ('subtitle_en', models.CharField(max_length=255, null=True)),
                ('subtitle_ru', models.CharField(max_length=255, null=True)),
                ('subtitle_uz', models.CharField(max_length=255, null=True)),
                ('body_text', models.TextField()),
                ('body_text_en', models.TextField(null=True)),
                ('body_text_ru', models.TextField(null=True)),
                ('body_text_uz', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('URL', models.URLField()),
            ],
        ),
    ]
