# Generated by Django 5.0.6 on 2024-07-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('body_text', models.TextField()),
                ('body_text_en', models.TextField(null=True)),
                ('body_text_ru', models.TextField(null=True)),
                ('body_text_uz', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company_License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('about', models.TextField()),
                ('about_en', models.TextField(null=True)),
                ('about_ru', models.TextField(null=True)),
                ('about_uz', models.TextField(null=True)),
                ('license', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Our_Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ImageField(upload_to='')),
            ],
        ),
    ]
